name: Daily Duck Facts

on:
  schedule:
    - cron: '0 15 * * *' # Runs daily at 15:00 UTC (adjust if needed)
  workflow_dispatch: # Allows manual run from GitHub

jobs:
  send-duck-facts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          TEXTBELT_KEY: ${{ secrets.TEXTBELT_KEY }}
        run: python main.py